
import DbConnection.CrudUtil;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mr.Secreti
 */
public class AddSubject extends javax.swing.JFrame {

    /**
     * Creates new form AddSubject
     */
    public AddSubject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnMinimize = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        subid = new javax.swing.JTextField();
        subName = new javax.swing.JTextField();
        SubSName = new javax.swing.JTextField();
        SubWeight = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        se = new javax.swing.JCheckBox();
        is = new javax.swing.JCheckBox();
        cs = new javax.swing.JCheckBox();
        btnSearch = new javax.swing.JButton();
        txtAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtDel = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(840, 540));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,210));

        jButton1.setBackground(new java.awt.Color(51, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentapplication/images/1741314_graduate_graduate cap_student_icon (1).png"))); // NOI18N
        jLabel2.setText("USJC STUDENT MANAGEMENT SYSTEM");

        BtnMinimize.setBackground(new java.awt.Color(0, 0, 51));
        BtnMinimize.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BtnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        BtnMinimize.setText("-");
        BtnMinimize.setBorder(null);
        BtnMinimize.setBorderPainted(false);
        BtnMinimize.setFocusPainted(false);
        BtnMinimize.setFocusable(false);
        BtnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinimizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 384, Short.MAX_VALUE)
                .addComponent(BtnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 840, 50));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0,190));

        subid.setBackground(new java.awt.Color(0, 0, 0));
        subid.setForeground(new java.awt.Color(255, 255, 255));
        subid.setText("Enter Subject id");
        subid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                subidFocusLost(evt);
            }
        });
        subid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subidActionPerformed(evt);
            }
        });
        subid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                subidKeyPressed(evt);
            }
        });

        subName.setBackground(new java.awt.Color(0, 0, 0));
        subName.setForeground(new java.awt.Color(255, 255, 255));
        subName.setText("Enter Subject full name");
        subName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                subNameFocusLost(evt);
            }
        });
        subName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subNameActionPerformed(evt);
            }
        });
        subName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                subNameKeyPressed(evt);
            }
        });

        SubSName.setBackground(new java.awt.Color(0, 0, 0));
        SubSName.setForeground(new java.awt.Color(255, 255, 255));
        SubSName.setText("Enter Subject short name");
        SubSName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                SubSNameFocusLost(evt);
            }
        });
        SubSName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubSNameActionPerformed(evt);
            }
        });
        SubSName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SubSNameKeyPressed(evt);
            }
        });

        SubWeight.setBackground(new java.awt.Color(0, 0, 0));
        SubWeight.setForeground(new java.awt.Color(255, 255, 255));
        SubWeight.setText("Enter Subject Weight");
        SubWeight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                SubWeightFocusLost(evt);
            }
        });
        SubWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubWeightActionPerformed(evt);
            }
        });
        SubWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SubWeightKeyPressed(evt);
            }
        });

        jLabel3.setText("Select Deprtments");

        se.setText("Software Engineering");
        se.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seActionPerformed(evt);
            }
        });

        is.setText("Information System");
        is.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isActionPerformed(evt);
            }
        });

        cs.setText("Computer Science");
        cs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentapplication/images/326690_magnify_search_zoom_icon.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setBorder(null);
        btnSearch.setFocusPainted(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtAdd.setBackground(new java.awt.Color(0, 0, 0));
        txtAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtAdd.setForeground(new java.awt.Color(255, 255, 255));
        txtAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentapplication/images/211872_person_add_icon.png"))); // NOI18N
        txtAdd.setText("Add");
        txtAdd.setBorder(null);
        txtAdd.setFocusPainted(false);
        txtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentapplication/images/7106354_reload_data_infographic_update_element_icon.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(null);
        btnUpdate.setFocusPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtDel.setBackground(new java.awt.Color(0, 0, 0));
        txtDel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDel.setForeground(new java.awt.Color(255, 255, 255));
        txtDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentapplication/images/185090_delete_garbage_icon.png"))); // NOI18N
        txtDel.setText("Delete");
        txtDel.setBorder(null);
        txtDel.setFocusPainted(false);
        txtDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDelActionPerformed(evt);
            }
        });

        error.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        error.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(SubWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SubSName, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(subName, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(subid, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(se)
                        .addGap(18, 18, 18)
                        .addComponent(cs)
                        .addGap(18, 18, 18)
                        .addComponent(is)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(subid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SubSName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SubWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(se)
                    .addComponent(cs)
                    .addComponent(is))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(error)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 720, 420));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentapplication/images/243653_square_back_arrow_left_icon.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 43, 38));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentapplication/images/Morning-at-Jayewardenepura-University-artwork.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(840, 540));
        jLabel1.setMinimumSize(new java.awt.Dimension(840, 540));
        jLabel1.setPreferredSize(new java.awt.Dimension(840, 540));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinimizeActionPerformed

    }//GEN-LAST:event_BtnMinimizeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DashBoardMain dsbMain = new DashBoardMain();
        this.setVisible(false);
        dsbMain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void seActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seActionPerformed

    private void isActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isActionPerformed

    private void csActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csActionPerformed

    private void SubWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubWeightActionPerformed

    private void subNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subNameActionPerformed

    private void subidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subidActionPerformed

    private void subidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subidKeyPressed
        // TODO add your handling code here:
       if(subid.getText().equals("Enter Subject id")) {
           subid.setText(null);
       }
    }//GEN-LAST:event_subidKeyPressed

    private void subidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_subidFocusLost
        // TODO add your handling code here:
        if(subid.getText().equals("")){
            subid.setText("Enter Subject id");
        }
    }//GEN-LAST:event_subidFocusLost

    private void subNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subNameKeyPressed
        // TODO add your handling code here:
        if(subName.getText().equals("Enter Subject full name")){
            subName.setText(null);
        }
    }//GEN-LAST:event_subNameKeyPressed

    private void subNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_subNameFocusLost
        // TODO add your handling code here:
        if(subName.getText().equals("")){
            subName.setText("Enter Subject full name");
        }
    }//GEN-LAST:event_subNameFocusLost

    private void SubSNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubSNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubSNameActionPerformed

    private void SubSNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SubSNameKeyPressed
        // TODO add your handling code here:
        if(SubSName.getText().equals("Enter Subject short name")){
            SubSName.setText(null);
        }
    }//GEN-LAST:event_SubSNameKeyPressed

    private void SubSNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SubSNameFocusLost
        // TODO add your handling code here:
        if(SubSName.getText().equals("")){
            SubSName.setText("Enter Subject short name");
        }
    }//GEN-LAST:event_SubSNameFocusLost

    private void SubWeightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SubWeightKeyPressed
        // TODO add your handling code here:
        if(SubWeight.getText().equals("Enter Subject Weight")){
            SubWeight.setText(null);
        }
    }//GEN-LAST:event_SubWeightKeyPressed

    private void SubWeightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SubWeightFocusLost
        // TODO add your handling code here:
        if(SubWeight.getText().equals("")){
            SubWeight.setText("Enter Subject Weight");
        }
    }//GEN-LAST:event_SubWeightFocusLost

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try {
            String studentId = subid.getText();
            String query = "SELECT * FROM subject WHERE subject_id = ?";
//            ResultSet result1 = CrudUtil.execute(query, studentId);
              ResultSet result1 = CrudUtil.execute(query,studentId);

            if (result1.next()) {
                subName.setText(result1.getString("subject_name"));
                SubSName.setText(result1.getString("subject_short_name"));
                SubWeight.setText(result1.getString("subject_weight"));
//                SubWeight.setText(result1.getString("department"));
//                txtGpa.setText(result1.getString("student_gpa"));
            } else {
                error.setText("|Subject not found");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "There is some issue: " + ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddActionPerformed
        // TODO add your handling code here:
               String se1 ="";
               String cs1 ="";
               String is1 ="";
               String weight ="";
        try{
            String subid1 = subid.getText();
            String subName1=subName.getText();
            String subSName1=SubSName.getText();
            String subWeight1 = SubWeight.getText();


            if(!subid.getText().contains("SUB")){
                error.setText("Please check the Student Id");
            }else if(subName.equals("Enter student name")){

            }
            else{
                 if(se.isSelected() && cs.isSelected() && is.isSelected()){
                   se1 = se.getText(); 
                   cs1 =  cs.getText();
                   is1 =  is.getText();
                   weight = se1+","+cs1+","+is1;
                }else if(se.isSelected() && cs.isSelected()){
                   se1 = se.getText(); 
                   cs1 =  cs.getText();
                   weight =se1+","+cs1;
                }else if(se.isSelected() && is.isSelected()){
                   se1 = se.getText(); 
                   is1 =  is.getText();
                   weight = se1+","+ is1;
                }else if(cs.isSelected() && is.isSelected()){
                   cs1 =  cs.getText();
                   is1 =  is.getText();
                   weight = cs1+","+is1;
                }else if(se.isSelected()){
                    se1 =se.getText();
                    weight = se1;
                }else if(cs.isSelected()){
                    cs1 = cs.getText();
                    weight= cs1;
                }else if(is.isSelected()){
                    is1 =is.getText();
                    weight = is1;
                }else{
                    error.setText("select a department");
                }
                error.setText("");
                CrudUtil.execute("insert into subject values (?,?,?,?,?)", subid1, subName1, subSName1,subWeight1 ,weight);
                JOptionPane.showMessageDialog(null, "New subject added successfully!");
                subid.setText("Enter Subject id");
                subName.setText("Enter Subject full name");
                SubSName.setText("Enter Subject short name");
                SubWeight.setText("Enter Subject Weight");

            }
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null, "Enter all values" );
        }catch (SQLException | ClassNotFoundException ex) {
            //            Logger.getLogger(SingUpInterface.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "there is some issue:" + ex);
        }

    }//GEN-LAST:event_txtAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            String query = "UPDATE subject SET subject_name = ?,Subject_short_name = ? , subject_weight = ?  WHERE subject_id LIKE ?";
            CrudUtil.execute(query, subName.getText(),SubSName.getText(),SubWeight.getText(),subid.getText());
            JOptionPane.showMessageDialog(null, "data update successfully!!");
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "There is some issue: " + ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDelActionPerformed
        // TODO add your handling code here:
        try{
            String studentId = subid.getText();
            if(!subid.getText().contains("SUB")){
                error.setText("Please check the Student Id");
            }else{
                CrudUtil.execute("delete from studentdata where studetn_index like '"+studentId+"' " );
                JOptionPane.showMessageDialog(null, "Data Delete SuccessFully!!");
                subid.setText("Enter Subject id");
                subName.setText("Enter Subject full name");
                SubSName.setText("Enter Subject short name");
                SubWeight.setText("Enter Subject Weight");
            }
        }catch (SQLException | ClassNotFoundException ex) {
            //            Logger.getLogger(SingUpInterface.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "there is some issue:" + ex);
        }
    }//GEN-LAST:event_txtDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSubject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMinimize;
    private javax.swing.JTextField SubSName;
    private javax.swing.JTextField SubWeight;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox cs;
    private javax.swing.JLabel error;
    private javax.swing.JCheckBox is;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox se;
    private javax.swing.JTextField subName;
    private javax.swing.JTextField subid;
    private javax.swing.JButton txtAdd;
    private javax.swing.JButton txtDel;
    // End of variables declaration//GEN-END:variables
}
