
import DbConnection.CrudUtil;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Mr.Secreti
 */
public class DashBoard extends javax.swing.JFrame {

    private Object iconifyButton;
    private Object maximizeButton;

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnMinimize = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSub1 = new javax.swing.JTextField();
        txtSub2 = new javax.swing.JTextField();
        txtSub3 = new javax.swing.JTextField();
        txtGpa = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        txtAdd = new javax.swing.JButton();
        txtDel = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        mark1 = new javax.swing.JTextField();
        mark2 = new javax.swing.JTextField();
        mark3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(840, 540));
        jPanel1.setMinimumSize(new java.awt.Dimension(840, 540));
        jPanel1.setPreferredSize(new java.awt.Dimension(840, 540));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentapplication/images/243653_square_back_arrow_left_icon.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 43, 38));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,210));

        jButton1.setBackground(new java.awt.Color(51, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentapplication/images/1741314_graduate_graduate cap_student_icon (1).png"))); // NOI18N
        jLabel2.setText("USJC STUDENT MANAGEMENT SYSTEM");

        BtnMinimize.setBackground(new java.awt.Color(0, 0, 51));
        BtnMinimize.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BtnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        BtnMinimize.setText("-");
        BtnMinimize.setBorder(null);
        BtnMinimize.setBorderPainted(false);
        BtnMinimize.setFocusPainted(false);
        BtnMinimize.setFocusable(false);
        BtnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinimizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 384, Short.MAX_VALUE)
                .addComponent(BtnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 840, 50));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0,190));

        txtId.setBackground(new java.awt.Color(0, 0, 0));
        txtId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setText("Enter student ID");
        txtId.setAlignmentX(2.0F);
        txtId.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtId.setPreferredSize(new java.awt.Dimension(120, 34));
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });

        txtName.setBackground(new java.awt.Color(0, 0, 0));
        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setText("Enter student name");
        txtName.setAlignmentY(2.0F);
        txtName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtName.setPreferredSize(new java.awt.Dimension(141, 22));
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });

        txtSub1.setBackground(new java.awt.Color(0, 0, 0));
        txtSub1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSub1.setForeground(new java.awt.Color(255, 255, 255));
        txtSub1.setText("Enter 1st subject name");
        txtSub1.setAlignmentY(2.0F);
        txtSub1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtSub1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSub1FocusLost(evt);
            }
        });
        txtSub1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSub1KeyPressed(evt);
            }
        });

        txtSub2.setBackground(new java.awt.Color(0, 0, 0));
        txtSub2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSub2.setForeground(new java.awt.Color(255, 255, 255));
        txtSub2.setText("Enter 2nd subject name");
        txtSub2.setAlignmentY(2.0F);
        txtSub2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtSub2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSub2FocusLost(evt);
            }
        });
        txtSub2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSub2KeyPressed(evt);
            }
        });

        txtSub3.setBackground(new java.awt.Color(0, 0, 0));
        txtSub3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSub3.setForeground(new java.awt.Color(255, 255, 255));
        txtSub3.setText("Enter 3rd subject name");
        txtSub3.setAlignmentY(2.0F);
        txtSub3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtSub3.setPreferredSize(new java.awt.Dimension(164, 22));
        txtSub3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSub3FocusLost(evt);
            }
        });
        txtSub3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSub3KeyPressed(evt);
            }
        });

        txtGpa.setBackground(new java.awt.Color(0, 0, 0));
        txtGpa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtGpa.setForeground(new java.awt.Color(255, 255, 255));
        txtGpa.setText("Enter GPA of three subjects");
        txtGpa.setAlignmentY(2.0F);
        txtGpa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtGpa.setPreferredSize(new java.awt.Dimension(192, 22));
        txtGpa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGpaFocusLost(evt);
            }
        });
        txtGpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGpaActionPerformed(evt);
            }
        });
        txtGpa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGpaKeyPressed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentapplication/images/326690_magnify_search_zoom_icon.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setBorder(null);
        btnSearch.setFocusPainted(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtAdd.setBackground(new java.awt.Color(0, 0, 0));
        txtAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtAdd.setForeground(new java.awt.Color(255, 255, 255));
        txtAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentapplication/images/211872_person_add_icon.png"))); // NOI18N
        txtAdd.setText("Add");
        txtAdd.setBorder(null);
        txtAdd.setFocusPainted(false);
        txtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddActionPerformed(evt);
            }
        });

        txtDel.setBackground(new java.awt.Color(0, 0, 0));
        txtDel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDel.setForeground(new java.awt.Color(255, 255, 255));
        txtDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentapplication/images/185090_delete_garbage_icon.png"))); // NOI18N
        txtDel.setText("Delete");
        txtDel.setBorder(null);
        txtDel.setFocusPainted(false);
        txtDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDelActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentapplication/images/7106354_reload_data_infographic_update_element_icon.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(null);
        btnUpdate.setFocusPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        error.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        error.setForeground(new java.awt.Color(204, 0, 0));

        mark1.setBackground(new java.awt.Color(0, 0, 0));
        mark1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mark1.setForeground(new java.awt.Color(255, 255, 255));
        mark1.setText("Enter Mark");
        mark1.setAlignmentY(2.0F);
        mark1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        mark1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mark1FocusLost(evt);
            }
        });
        mark1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark1ActionPerformed(evt);
            }
        });
        mark1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mark1KeyPressed(evt);
            }
        });

        mark2.setBackground(new java.awt.Color(0, 0, 0));
        mark2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mark2.setForeground(new java.awt.Color(255, 255, 255));
        mark2.setText("Enter Mark");
        mark2.setAlignmentY(2.0F);
        mark2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        mark2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mark2FocusLost(evt);
            }
        });
        mark2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mark2KeyPressed(evt);
            }
        });

        mark3.setBackground(new java.awt.Color(0, 0, 0));
        mark3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mark3.setForeground(new java.awt.Color(255, 255, 255));
        mark3.setText("Enter Mark");
        mark3.setAlignmentY(2.0F);
        mark3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        mark3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mark3FocusLost(evt);
            }
        });
        mark3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mark3KeyPressed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Calculate GPA");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSub1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGpa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(txtSub3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSub2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mark1)
                                    .addComponent(mark2)
                                    .addComponent(mark3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSub1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mark1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSub2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mark2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSub3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mark3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(txtGpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 720, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentapplication/images/Morning-at-Jayewardenepura-University-artwork.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(840, 540));
        jLabel1.setMinimumSize(new java.awt.Dimension(840, 540));
        jLabel1.setPreferredSize(new java.awt.Dimension(840, 540));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinimizeActionPerformed

    }//GEN-LAST:event_BtnMinimizeActionPerformed

    private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
        // TODO add your handling code here:
        if(txtId.getText().equals(null)||txtId.getText().equals("")){
            txtId.setText("Enter student ID");
            txtId.requestFocus();
        }
    }//GEN-LAST:event_txtIdFocusLost

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        // TODO add your handling code here:
        if(txtName.getText().equals(null)||txtName.getText().equals("") ){
            txtName.setText("Enter student name");
            txtName.requestFocus();
        }
    }//GEN-LAST:event_txtNameFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
        // TODO add your handling code here:
        if(txtId.getText().equals("Enter student ID")){
            txtId.setText(null);
            txtId.requestFocus();
        }
    }//GEN-LAST:event_txtIdKeyPressed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
        if(txtName.getText().equals("Enter student name")){
            txtName.setText(null);
            txtName.requestFocus();
        }
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtSub1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSub1FocusLost
        // TODO add your handling code here:
        if(txtSub1.getText().equals("")){
            txtSub1.setText("Enter 1st subject name");
            txtSub1.requestFocus();
        }
    }//GEN-LAST:event_txtSub1FocusLost

    private void txtSub1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSub1KeyPressed
        // TODO add your handling code here:
        if(txtSub1.getText().equals("Enter 1st subject name")){
            txtSub1.setText(null);
            txtSub1.requestFocus();
        }
    }//GEN-LAST:event_txtSub1KeyPressed

    private void txtSub2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSub2FocusLost
        // TODO add your handling code here:
        if(txtSub2.getText().equals("")){
            txtSub2.setText("Enter 2nd subject name");
            txtSub2.requestFocus();
        }
    }//GEN-LAST:event_txtSub2FocusLost

    private void txtSub2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSub2KeyPressed
        // TODO add your handling code here:
        if(txtSub2.getText().equals("Enter 2nd subject name")){
            txtSub2.setText(null);
            txtSub2.requestFocus();
        }
    }//GEN-LAST:event_txtSub2KeyPressed

    private void txtSub3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSub3FocusLost
        // TODO add your handling code here:
        if(txtSub3.getText().equals("")){
            txtSub3.setText("Enter 3rd subject name");
            txtSub3.requestFocus();
        }
    }//GEN-LAST:event_txtSub3FocusLost

    private void txtSub3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSub3KeyPressed
        // TODO add your handling code here:
        if(txtSub3.getText().equals("Enter 3rd subject name")){
            txtSub3.setText(null);
            txtSub3.requestFocus();
        }
    }//GEN-LAST:event_txtSub3KeyPressed

    private void txtGpaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGpaFocusLost
        // TODO add your handling code here:
        if(txtGpa.getText().equals("")){
            txtGpa.setText("Enter GPA of three subjects");
            txtGpa.requestFocus();
        }
    }//GEN-LAST:event_txtGpaFocusLost

    private void txtGpaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGpaKeyPressed
        // TODO add your handling code here:
        if(txtGpa.getText().equals("Enter GPA of three subjects")){
            txtGpa.setText(null);
            txtGpa.requestFocus();
        }
    }//GEN-LAST:event_txtGpaKeyPressed

    private void txtGpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGpaActionPerformed

    private void txtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddActionPerformed
        // TODO add your handling code here:
        try{
            String studentId = txtId.getText();
            String studentName=txtName.getText();
            String subject1=txtSub1.getText();
            String subject2 = txtSub2.getText();
            String subject3 = txtSub3.getText();
            String gpa =  txtGpa.getText();
                   
            
            if(!txtId.getText().contains("FC110")){
                error.setText("Please check the Student Id");
            }else if(studentName.equals("Enter student name")){
            
            }
            else if(Float.parseFloat(txtGpa.getText())>= 4 && Float.parseFloat(txtGpa.getText())<=0){
                JOptionPane.showMessageDialog(null, "Check GPA value");
            }
//            else if(!isNumeric(txtGpa.getText()) ){
//                JOptionPane.showMessageDialog(null, "GPA value must Numeric");
//            }
            else{
                error.setText("");
                CrudUtil.execute("insert into studentdata(studetn_index,student_name,subject_one,subject_two,subject_three,student_gpa ) values (?,?,?,?,?,?)", studentId, studentName, subject1,subject2,subject3,gpa);   
                JOptionPane.showMessageDialog(null, "New member added successfully!");
                txtId.setText("Enter student ID");
                txtName.setText("Enter student name");
                txtSub1.setText("Enter 1st subject name");
                txtSub2.setText("Enter 2nd subject name");
                txtSub3.setText("Enter 3rd subject name");
                txtGpa.setText("Enter GPA of three subjects");
            }
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null, "Enter all values" );
        }catch (SQLException | ClassNotFoundException ex) {
//            Logger.getLogger(SingUpInterface.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(null, "there is some issue:" + ex);
        }
        
    }//GEN-LAST:event_txtAddActionPerformed

    private void txtDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDelActionPerformed
        // TODO add your handling code here:
        try{
            String studentId = txtId.getText();
            if(!txtId.getText().contains("FC110")){
                error.setText("Please check the Student Id");
            }else{
                CrudUtil.execute("delete from studentdata where studetn_index like '"+studentId+"' " );  
                JOptionPane.showMessageDialog(null, "Data Delete SuccessFully!!");    
                txtId.setText("Enter student ID");
                txtName.setText("Enter student name");
                txtSub1.setText("Enter 1st subject name");
                txtSub2.setText("Enter 2nd subject name");
                txtSub3.setText("Enter 3rd subject name");
                txtGpa.setText("Enter GPA of three subjects");
            }
        }catch (SQLException | ClassNotFoundException ex) {
//            Logger.getLogger(SingUpInterface.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(null, "there is some issue:" + ex);
        }
    }//GEN-LAST:event_txtDelActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try {
            error.setText("");
            String studentId = txtId.getText();
            String query = "SELECT * FROM studentData WHERE studetn_index = ?";
            ResultSet result1 = CrudUtil.execute(query, studentId);

            if (result1.next()) {
                txtName.setText(result1.getString("student_name"));
                txtSub1.setText(result1.getString("subject_one"));
                txtSub2.setText(result1.getString("subject_two"));
                txtSub3.setText(result1.getString("subject_three"));
                txtGpa.setText(result1.getString("student_gpa"));
            } else {
                error.setText("Student not found");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "There is some issue: " + ex);
        }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    try {
        error.setText("");
        String query = "UPDATE studentData SET student_name = ?,subject_one = ? , subject_two = ? , subject_three = ? , student_gpa = ? WHERE studetn_index LIKE ?";
        CrudUtil.execute(query, txtName.getText(),txtSub1.getText(),txtSub2.getText(),txtSub3.getText(),txtGpa.getText(), "%" + txtId.getText() + "%");
        JOptionPane.showMessageDialog(null, "data update successfully!!");
    } catch (SQLException | ClassNotFoundException ex) {
        JOptionPane.showMessageDialog(null, "There is some issue: " + ex);
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DashBoardMain dsbMain = new DashBoardMain();
        this.setVisible(false);
        dsbMain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mark1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mark1FocusLost
        // TODO add your handling code here:
                if(mark1.getText().equals("")){
            mark1.setText("Enter Mark");
       }
    }//GEN-LAST:event_mark1FocusLost

    private void mark1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mark1KeyPressed
        // TODO add your handling code here:
        if(mark1.getText().equals("Enter Mark")){
            mark1.setText(null);
       }
    }//GEN-LAST:event_mark1KeyPressed

    private void mark2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mark2FocusLost
        // TODO add your handling code here:
                        if(mark2.getText().equals("")){
            mark2.setText("Enter Mark");
       }
    }//GEN-LAST:event_mark2FocusLost

    private void mark2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mark2KeyPressed
        // TODO add your handling code here:
                if(mark2.getText().equals("Enter Mark")){
            mark2.setText(null);
       }
    }//GEN-LAST:event_mark2KeyPressed

    private void mark3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mark3FocusLost
        // TODO add your handling code here:
                        if(mark3.getText().equals("")){
            mark3.setText("Enter Mark");
       }
    }//GEN-LAST:event_mark3FocusLost

    private void mark3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mark3KeyPressed
        // TODO add your handling code here:
                if(mark3.getText().equals("Enter Mark")){
            mark3.setText(null);
       }
    }//GEN-LAST:event_mark3KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String m1 = mark1.getText();
        String m2 =mark2.getText();
        String m3 = mark3.getText();
        
            try {
            String studentId = txtId.getText();
            String query = "SELECT * FROM subject WHERE subject_short_name = ?";
            ResultSet result1 = CrudUtil.execute(query, txtSub1.getText());
            ResultSet result2 = CrudUtil.execute(query, txtSub2.getText());
            ResultSet result3 = CrudUtil.execute(query, txtSub3.getText());
            
            if(m1.equals("")){
                error.setText("enter mark 1");
            }else if(m2.equals("")){
                error.setText("Enter mark 2");
            }else if(m3.equals("")){
                error.setText("Enter mark 3");
            }
            else if (result1.next() && result2.next() && result3.next()) {
                int ma1 = Integer.parseInt( result1.getString("subject_weight"));
                int ma2 = Integer.parseInt(result2.getString("subject_weight"));
                int ma3 = Integer.parseInt(result3.getString("subject_weight"));
                double result =(double) ((Float.parseFloat(m1) * ma1) + (Float.parseFloat(m2) * ma2) + (Float.parseFloat(m3) * ma3)) / (ma1 + ma2 + ma3);

//                int answer = (Integer.parseInt(m1) * ma1) +(Integer.parseInt(m2)* ma2) + (Integer.parseInt(m3)* ma3))/(ma1 +ma2+ma3);
                txtGpa.setText(String.valueOf(result));

            }
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "There is some issue: " + ex);
        }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void mark1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mark1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMinimize;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel error;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField mark1;
    private javax.swing.JTextField mark2;
    private javax.swing.JTextField mark3;
    private javax.swing.JButton txtAdd;
    private javax.swing.JButton txtDel;
    private javax.swing.JTextField txtGpa;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSub1;
    private javax.swing.JTextField txtSub2;
    private javax.swing.JTextField txtSub3;
    // End of variables declaration//GEN-END:variables

    private boolean isNumeric(String text) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
